<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/vibhor/Documents/Projects/Story/Threlte/static/models/chandrayan.glb --root /models/ --printwidth 120 --precision 2
Author: akareactor (https://sketchfab.com/akareactor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isro-chandrayyan-3-mission-lander-module-vikram-27e8d9b94f324e6b9a25b58e64317213
Title: ISRO Chandrayyan-3 Mission Lander Module Vikram
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/chandrayan.glb')
  gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
	});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.VikramDoor_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 1.57, -1.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramNose001_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 0.67, -0.82]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramSocket_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 0.65, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['Vikram������������_������������_Vikram_0'].geometry}
      material={gltf.materials.Vikram}
      position={[0, 1.1, -0.82]}
    />
    <T.Mesh
      geometry={gltf.nodes['VikramBody������������������������_Vikram_0'].geometry}
      material={gltf.materials.Vikram}
    />
    <T.Mesh geometry={gltf.nodes.VikramOriNose_Vikram_0.geometry} material={gltf.materials.Vikram} />
    <T.Mesh
      geometry={gltf.nodes.VikramNose002_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.8, 0.67, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramNose003_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 0.67, 0.8]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramNose004_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.8, 0.67, 0]}
    />
    <T.Mesh geometry={gltf.nodes.VikramDoorFastener_Vikram_0.geometry} material={gltf.materials.Vikram} />
    <T.Mesh
      geometry={gltf.nodes.VikramLegJoint_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, -0.01, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramSolarPanelLeft_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.88, 1.7, -0.16]}
      rotation={[0, 0, 0.3]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramSolarPanelRight_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.89, 1.61, -0.3]}
      rotation={[0, 0, -0.3]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramSolarPanelBack_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 1.71, 1.04]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyCoreFoil_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 2.17, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartStarSensor_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.55, 2.15, -1.11]}
      rotation={[0.33, 0.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartLHVC_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.39, 2.13, 1.44]}
      rotation={[Math.PI / 2, 0, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPart004_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0, 2.41, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartLDV_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.8, 2.12, 0.8]}
      rotation={[-0.5, -0.15, -1.31]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartLASA_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[1.01, 1.31, 0.79]}
      rotation={[-1.12, -0.32, -1.45]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartKaRA_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.64, 1.3, 1.03]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartReactionWheels_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.34, 2.44, 0.38]}
      rotation={[Math.PI, 1.34, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyLRA_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[0.15, 2.94, -0.7]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramSolarPanelRightHolder_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.83, 1.67, -1.31]}
      rotation={[-Math.PI / 2, -1.27, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPayload_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.27, 1.9, 1.03]}
      rotation={[0.78, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramBodyPartLHDAC_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      position={[-0.88, 1.31, 1.07]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
    />
    <T.Mesh geometry={gltf.nodes.VikramFootPad001_Vikram_0.geometry} material={gltf.materials.Vikram} />
    <T.Mesh
      geometry={gltf.nodes.VikramFootPad002_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      rotation={[0, Math.PI / 2, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramFootPad003_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.VikramFootPad004_Vikram_0.geometry}
      material={gltf.materials.Vikram}
      rotation={[0, -Math.PI / 2, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
