<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/vibhor/Documents/Projects/Story/Threlte/static/models/mangalayan.glb --root /models/ --printwidth 120 --precision 2
Author: aods (https://sketchfab.com/aods)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/nasas-3d-rover-d915dc6de3914ad78235b4c69df65f94
Title: NASA's 3d Rover
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/mangalayan.glb')
  gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
	});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-0.08, 0.09, 0.01]} rotation={[Math.PI / 2, 0, -Math.PI]}>
      <T.Mesh geometry={gltf.nodes.primitive_0.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_1.geometry} material={gltf.materials.iron} />
    </T.Group>
    <T.Group rotation={[-1.41, -0.02, -1.69]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_1.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_1_1.geometry} material={gltf.materials.glass_lens} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.arm_02_001_1.geometry}
      material={gltf.materials.iron}
      position={[-0.08, 0.09, 0.01]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.arm_02_pivot_1.geometry}
      material={gltf.materials.transparent}
      position={[0, 0, 0.11]}
      rotation={[Math.PI / 2, 0, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.arm_01_1.geometry}
      material={gltf.materials.gunmetal}
      position={[-0.07, -0.05, 0]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
      scale={0}
    />
    <T.Mesh
      geometry={gltf.nodes.arm_01_pivot_1.geometry}
      material={gltf.materials.transparent}
      position={[-0.01, 0, 0.04]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Group position={[-0.02, 1.16, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_2.geometry} material={gltf.materials.mars_2020_03} />
      <T.Mesh geometry={gltf.nodes.primitive_1_2.geometry} material={gltf.materials.mars_2020_01} />
      <T.Mesh geometry={gltf.nodes.primitive_2.geometry} material={gltf.materials.mars_2020_04} />
      <T.Mesh geometry={gltf.nodes.primitive_3.geometry} material={gltf.materials.mars_2020_02} />
      <T.Mesh geometry={gltf.nodes.primitive_4.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_5.geometry} material={gltf.materials.mars_2020_04_aluminum_r} />
    </T.Group>
    <T.Group position={[-0.08, 0.72, 0.97]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_3.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_1_3.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_2_1.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_3_1.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_4_1.geometry} material={gltf.materials.spring} />
      <T.Mesh geometry={gltf.nodes.primitive_5_1.geometry} material={gltf.materials.mars_2020_06_brass2} />
    </T.Group>
    <T.Group position={[0.09, 0.68, 0.98]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_4.geometry} material={gltf.materials.aluminum_black_001} />
      <T.Mesh geometry={gltf.nodes.primitive_1_4.geometry} material={gltf.materials.mars_2020_04_001} />
    </T.Group>
    <T.Group position={[0.47, 0.78, -1.14]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_5.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_1_5.geometry} material={gltf.materials.mars_2020_06_brass2} />
      <T.Mesh geometry={gltf.nodes.primitive_2_2.geometry} material={gltf.materials.grey_brushed} />
      <T.Mesh geometry={gltf.nodes.primitive_3_2.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_4_2.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_5_2.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_6.geometry} material={gltf.materials.spring} />
    </T.Group>
    <T.Group position={[0.51, 0.82, -1.22]} rotation={[-Math.PI / 4, -0.38, 0]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_6.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_1_6.geometry} material={gltf.materials.mars_2020_04} />
    </T.Group>
    <T.Group position={[-0.51, 0.82, -1.22]} rotation={[2.36, -0.38, -Math.PI]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_7.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_1_7.geometry} material={gltf.materials.mars_2020_04} />
    </T.Group>
    <T.Group position={[0, 0.26, -0.03]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_8.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_1_8.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_2_3.geometry} material={gltf.materials.material} />
    </T.Group>
    <T.Group position={[0, 0.71, -0.03]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_9.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_1_9.geometry} material={gltf.materials.mars_2020_05_gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_4.geometry} material={gltf.materials.gunmetal_dark} />
      <T.Mesh geometry={gltf.nodes.primitive_3_3.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_4_3.geometry} material={gltf.materials.gray_krinkle} />
      <T.Mesh geometry={gltf.nodes.primitive_5_3.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_6_1.geometry} material={gltf.materials.mars_2020_gunmetal_dark} />
    </T.Group>
    <T.Group position={[-0.01, 0.96, 1.12]} rotation={[-Math.PI, 0, 0]} scale={0.03}>
      <T.Mesh geometry={gltf.nodes.primitive_0_10.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_1_10.geometry} material={gltf.materials.gunmetal_dark} />
    </T.Group>
    <T.Group position={[0.45, 0.91, 1.18]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.03}>
      <T.Group position={[-4.95, 2.75, 2.32]} rotation={[0, 0, -0.28]}>
        <T.Group position={[-23.49, -6.82, 0.65]} rotation={[0, 0, -1.26]}>
          <T.Group position={[22.47, -0.72, 0.57]} rotation={[0, 0, 1.54]}>
            <T.Group position={[5.24, -4.55, 1.8]} rotation={[-3.14, -1.41, 0]} scale={29.85}>
              <T.Group position={[-0.03, 0.18, 0.23]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_84.geometry} material={gltf.materials.aluminum} />
                <T.Mesh geometry={gltf.nodes.primitive_1_84.geometry} material={gltf.materials.gunmetal} />
              </T.Group>
              <T.Group position={[0.29, 0.17, 0.17]} rotation={[-Math.PI, 0.02, -Math.PI]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_85.geometry} material={gltf.materials.gunmetal} />
                <T.Mesh geometry={gltf.nodes.primitive_1_85.geometry} material={gltf.materials.glass_2} />
              </T.Group>
              <T.Group position={[0.33, 0.22, -0.09]} rotation={[-Math.PI, 0.02, -Math.PI]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_86.geometry} material={gltf.materials.gunmetal} />
                <T.Mesh geometry={gltf.nodes.primitive_1_86.geometry} material={gltf.materials.glass_2} />
              </T.Group>
              <T.Group position={[-0.24, 0.17, -0.04]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_87.geometry} material={gltf.materials.paint_white_base} />
                <T.Mesh geometry={gltf.nodes.primitive_1_87.geometry} material={gltf.materials.mars_2020_05} />
                <T.Mesh geometry={gltf.nodes.primitive_2_57.geometry} material={gltf.materials.glass_2} />
              </T.Group>
              <T.Group position={[0.23, 0.18, 0.05]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_88.geometry} material={gltf.materials.iron} />
                <T.Mesh geometry={gltf.nodes.primitive_1_88.geometry} material={gltf.materials.gunmetal_dark} />
                <T.Mesh geometry={gltf.nodes.primitive_2_58.geometry} material={gltf.materials.glass_2} />
                <T.Mesh geometry={gltf.nodes.primitive_3_45.geometry} material={gltf.materials.gunmetal} />
              </T.Group>
              <T.Group position={[0.23, 0.18, 0.05]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_89.geometry} material={gltf.materials.gunmetal} />
                <T.Mesh geometry={gltf.nodes.primitive_1_89.geometry} material={gltf.materials.gunmetal_dark} />
              </T.Group>
              <T.Group position={[0.23, 0.18, 0.05]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_90.geometry} material={gltf.materials.gunmetal_dark} />
                <T.Mesh geometry={gltf.nodes.primitive_1_90.geometry} material={gltf.materials.aluminum} />
                <T.Mesh geometry={gltf.nodes.primitive_2_59.geometry} material={gltf.materials.gunmetal} />
              </T.Group>
              <T.Group position={[0.31, 0.19, -0.06]}>
                <T.Mesh geometry={gltf.nodes.primitive_0_91.geometry} material={gltf.materials.gunmetal_dark} />
                <T.Mesh geometry={gltf.nodes.primitive_1_91.geometry} material={gltf.materials.iron} />
                <T.Mesh geometry={gltf.nodes.primitive_2_60.geometry} material={gltf.materials.glass_2} />
                <T.Mesh geometry={gltf.nodes.primitive_3_46.geometry} material={gltf.materials.gunmetal} />
              </T.Group>
              <T.Mesh geometry={gltf.nodes.primitive_0_82.geometry} material={gltf.materials.gunmetal} />
              <T.Mesh geometry={gltf.nodes.primitive_1_82.geometry} material={gltf.materials.gunmetal_dark} />
              <T.Mesh geometry={gltf.nodes.primitive_2_55.geometry} material={gltf.materials.Material} />
              <T.Mesh geometry={gltf.nodes.primitive_3_43.geometry} material={gltf.materials.foil_orange} />
              <T.Mesh geometry={gltf.nodes.primitive_4_33.geometry} material={gltf.materials.aluminum} />
              <T.Mesh geometry={gltf.nodes.primitive_5_31.geometry} material={gltf.materials.paint_white_base} />
              <T.Mesh geometry={gltf.nodes.primitive_6_21.geometry} material={gltf.materials.bronze} />
              <T.Mesh geometry={gltf.nodes.primitive_7_13.geometry} material={gltf.materials.mars_2020_07} />
              <T.Mesh geometry={gltf.nodes.primitive_8_8.geometry} material={gltf.materials.mars_2020_06} />
              <T.Mesh geometry={gltf.nodes.primitive_9_4.geometry} material={gltf.materials.arm_graphics} />
              <T.Mesh
                geometry={gltf.nodes.hinge_1.geometry}
                material={gltf.materials.transparent}
                position={[-0.32, 0.14, -0.04]}
                rotation={[2.49, -1.37, 0.93]}
              />
              <T.Mesh
                geometry={gltf.nodes.turret_obj_006_1.geometry}
                material={gltf.materials.gunmetal_dark}
                position={[0.23, 0.18, 0.05]}
              />
            </T.Group>
            <T.Mesh geometry={gltf.nodes.primitive_0_73.geometry} material={gltf.materials.gunmetal} />
            <T.Mesh geometry={gltf.nodes.primitive_1_73.geometry} material={gltf.materials.gunmetal_dark} />
          </T.Group>
          <T.Mesh geometry={gltf.nodes.primitive_0_42.geometry} material={gltf.materials.gunmetal_dark} />
          <T.Mesh geometry={gltf.nodes.primitive_1_42.geometry} material={gltf.materials.paint_white_base} />
          <T.Mesh geometry={gltf.nodes.primitive_2_27.geometry} material={gltf.materials.mars_2020_07} />
          <T.Mesh geometry={gltf.nodes.primitive_3_21.geometry} material={gltf.materials.gunmetal} />
          <T.Mesh geometry={gltf.nodes.primitive_4_16.geometry} material={gltf.materials.foil_orange} />
          <T.Mesh geometry={gltf.nodes.primitive_5_15.geometry} material={gltf.materials.arm_graphics} />
          <T.Mesh geometry={gltf.nodes.primitive_6_10.geometry} material={gltf.materials.mars_2020_02_n} />
          <T.Mesh geometry={gltf.nodes.primitive_7_6.geometry} material={gltf.materials.bronze} />
        </T.Group>
        <T.Mesh geometry={gltf.nodes.primitive_0_34.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_1_34.geometry} material={gltf.materials.gunmetal_dark} />
        <T.Mesh geometry={gltf.nodes.primitive_2_21.geometry} material={gltf.materials.mars_2020_07} />
        <T.Mesh geometry={gltf.nodes.primitive_3_15.geometry} material={gltf.materials.gunmetal} />
        <T.Mesh geometry={gltf.nodes.primitive_4_12.geometry} material={gltf.materials.arm_graphics} />
        <T.Mesh geometry={gltf.nodes.primitive_5_11.geometry} material={gltf.materials.mars_2020_02_n} />
        <T.Mesh geometry={gltf.nodes.primitive_6_7.geometry} material={gltf.materials.bronze} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.primitive_0_11.geometry} material={gltf.materials.gunmetal_dark} />
      <T.Mesh geometry={gltf.nodes.primitive_1_11.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_5.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_3_4.geometry} material={gltf.materials.foil_orange} />
    </T.Group>
    <T.Group position={[-0.02, 1.13, 0.81]} rotation={[2.71, -0.77, 0.43]} scale={[0.14, 0.25, 0.14]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_12.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_1_12.geometry} material={gltf.materials.mars_2020_05_aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_2_6.geometry} material={gltf.materials.mars_2020_05_brass} />
      <T.Mesh geometry={gltf.nodes.primitive_3_5.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_4_4.geometry} material={gltf.materials.mars_2020_05_gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_5_4.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_6_2.geometry} material={gltf.materials.mars_2020_01} />
      <T.Mesh geometry={gltf.nodes.primitive_7.geometry} material={gltf.materials.arm_graphics} />
      <T.Mesh geometry={gltf.nodes.primitive_8.geometry} material={gltf.materials.spring} />
    </T.Group>
    <T.Group position={[0, 1.16, -1.25]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_13.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_1_13.geometry} material={gltf.materials.mars_2020_05_cooling_lines} />
      <T.Mesh geometry={gltf.nodes.primitive_2_7.geometry} material={gltf.materials.mars_2020_04} />
      <T.Mesh geometry={gltf.nodes.primitive_3_6.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_4_5.geometry} material={gltf.materials.mars_2020_06_brass2} />
      <T.Mesh geometry={gltf.nodes.primitive_5_5.geometry} material={gltf.materials.copper} />
      <T.Mesh geometry={gltf.nodes.primitive_6_3.geometry} material={gltf.materials.mars_2020_03} />
      <T.Mesh geometry={gltf.nodes.primitive_7_1.geometry} material={gltf.materials.array_gold_trim} />
      <T.Mesh geometry={gltf.nodes.primitive_8_1.geometry} material={gltf.materials.gold} />
      <T.Mesh geometry={gltf.nodes.primitive_9.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_10.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_11.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_12.geometry} material={gltf.materials.gunmetal_dark} />
    </T.Group>
    <T.Group position={[-0.5, 1.64, -1.08]} scale={[0.08, 0.09, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_14.geometry} material={gltf.materials.black_krinkle} />
      <T.Mesh geometry={gltf.nodes.primitive_1_14.geometry} material={gltf.materials.gunmetal_dark} />
    </T.Group>
    <T.Group position={[0.42, 1.28, -0.39]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_15.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_15.geometry} material={gltf.materials.mars_2020_01} />
      <T.Mesh geometry={gltf.nodes.primitive_2_8.geometry} material={gltf.materials.brass} />
      <T.Mesh geometry={gltf.nodes.primitive_3_7.geometry} material={gltf.materials.gunmetal} />
    </T.Group>
    <T.Group position={[0.49, 1.51, -0.94]} rotation={[-Math.PI, 0, 0]} scale={0}>
      <T.Mesh geometry={gltf.nodes.primitive_0_16.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_1_16.geometry} material={gltf.materials.mars_2020_06_brass2} />
    </T.Group>
    <T.Group position={[0.61, 0.71, 0.83]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_17.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_17.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_9.geometry} material={gltf.materials.grey_brushed} />
    </T.Group>
    <T.Group position={[-0.61, 0.72, 0.83]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_18.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_18.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_10.geometry} material={gltf.materials.grey_brushed} />
    </T.Group>
    <T.Group position={[-0.02, 1.16, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_19.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_19.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_2_11.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_3_8.geometry} material={gltf.materials.gunmetal_dark} />
    </T.Group>
    <T.Group position={[0, 1.46, -0.91]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_20.geometry} material={gltf.materials.mars_2020_04} />
      <T.Mesh geometry={gltf.nodes.primitive_1_20.geometry} material={gltf.materials.arm_graphics} />
      <T.Mesh geometry={gltf.nodes.primitive_2_12.geometry} material={gltf.materials.grey_brushed} />
      <T.Mesh geometry={gltf.nodes.primitive_3_9.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_4_6.geometry} material={gltf.materials.glass_2} />
      <T.Mesh geometry={gltf.nodes.primitive_5_6.geometry} material={gltf.materials.nameplate} />
    </T.Group>
    <T.Group position={[-0.63, 1.24, 0.61]}>
      <T.Group position={[-0.04, 0.36, 0.13]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_35.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_1_35.geometry} material={gltf.materials.mars_2020_03} />
      </T.Group>
      <T.Group position={[0.07, 0.25, 0.08]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_36.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_1_36.geometry} material={gltf.materials.bronze} />
        <T.Mesh geometry={gltf.nodes.primitive_2_22.geometry} material={gltf.materials.aluminum} />
        <T.Mesh geometry={gltf.nodes.primitive_3_16.geometry} material={gltf.materials.mars_2020_01_n} />
      </T.Group>
      <T.Group position={[-0.14, 0.37, -0.06]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_37.geometry} material={gltf.materials.aluminum_003} />
        <T.Mesh geometry={gltf.nodes.primitive_1_37.geometry} material={gltf.materials.mars_2020_03_002} />
      </T.Group>
      <T.Group position={[0.07, 0.55, 0.11]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_38.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_1_38.geometry} material={gltf.materials.gunmetal} />
        <T.Mesh geometry={gltf.nodes.primitive_2_23.geometry} material={gltf.materials.mars_2020_06_brass2} />
        <T.Mesh geometry={gltf.nodes.primitive_3_17.geometry} material={gltf.materials.mars_2020_01_n} />
        <T.Mesh geometry={gltf.nodes.primitive_4_13.geometry} material={gltf.materials.bronze} />
        <T.Mesh geometry={gltf.nodes.primitive_5_12.geometry} material={gltf.materials.gunmetal_dark} />
        <T.Mesh geometry={gltf.nodes.primitive_6_8.geometry} material={gltf.materials.aluminum_001} />
        <T.Mesh geometry={gltf.nodes.primitive_7_5.geometry} material={gltf.materials.mars_2020_02_n} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.primitive_0_21.geometry} material={gltf.materials.mars_2020_01_n} />
      <T.Mesh geometry={gltf.nodes.primitive_1_21.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_13.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_3_10.geometry} material={gltf.materials.mars_2020_06_brass2} />
      <T.Mesh geometry={gltf.nodes.primitive_4_7.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_5_7.geometry} material={gltf.materials.mars_2020_02_n} />
      <T.Mesh geometry={gltf.nodes.primitive_6_4.geometry} material={gltf.materials.bronze} />
      <T.Mesh geometry={gltf.nodes.primitive_7_2.geometry} material={gltf.materials.blades} />
    </T.Group>
    <T.Group position={[-0.52, 1.92, 0.71]}>
      <T.Group position={[0.08, 0.21, 0.07]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_39.geometry} material={gltf.materials.gunmetal} />
        <T.Mesh geometry={gltf.nodes.primitive_1_39.geometry} material={gltf.materials.mars_2020_02} />
        <T.Mesh geometry={gltf.nodes.primitive_2_24.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_3_18.geometry} material={gltf.materials.glass_2} />
      </T.Group>
      <T.Group position={[-0.03, 0.14, 0]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_40.geometry} material={gltf.materials.mars_2020_02} />
        <T.Mesh geometry={gltf.nodes.primitive_1_40.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_2_25.geometry} material={gltf.materials.mars_2020_06_brass2} />
        <T.Mesh geometry={gltf.nodes.primitive_3_19.geometry} material={gltf.materials.aluminum_black} />
        <T.Mesh geometry={gltf.nodes.primitive_4_14.geometry} material={gltf.materials.gunmetal} />
        <T.Mesh geometry={gltf.nodes.primitive_5_13.geometry} material={gltf.materials.glass_2} />
      </T.Group>
      <T.Group position={[-0.03, 0.05, 0.05]}>
        <T.Mesh geometry={gltf.nodes.primitive_0_41.geometry} material={gltf.materials.paint_white_base} />
        <T.Mesh geometry={gltf.nodes.primitive_1_41.geometry} material={gltf.materials.mars_2020_02} />
        <T.Mesh geometry={gltf.nodes.primitive_2_26.geometry} material={gltf.materials.aluminum_black} />
        <T.Mesh geometry={gltf.nodes.primitive_3_20.geometry} material={gltf.materials.mars_2020_05} />
        <T.Mesh geometry={gltf.nodes.primitive_4_15.geometry} material={gltf.materials.glass_2} />
        <T.Mesh geometry={gltf.nodes.primitive_5_14.geometry} material={gltf.materials.aluminum} />
        <T.Mesh geometry={gltf.nodes.primitive_6_9.geometry} material={gltf.materials.mars_2020_06_brass2} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.primitive_0_22.geometry} material={gltf.materials.mars_2020_02} />
      <T.Mesh geometry={gltf.nodes.primitive_1_22.geometry} material={gltf.materials.mars_2020_03} />
      <T.Mesh geometry={gltf.nodes.primitive_2_14.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_3_11.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_4_8.geometry} material={gltf.materials.bronze} />
      <T.Mesh geometry={gltf.nodes.primitive_5_8.geometry} material={gltf.materials.mars_2020_06_brass2} />
      <T.Mesh geometry={gltf.nodes.primitive_6_5.geometry} material={gltf.materials.mars_2020_01_n} />
      <T.Mesh geometry={gltf.nodes.primitive_7_3.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_8_2.geometry} material={gltf.materials.mars_2020_02_n} />
      <T.Mesh
        geometry={gltf.nodes.microphones_001_1.geometry}
        material={gltf.materials.grey_brushed}
        position={[0.02, 0.15, 0.12]}
      />
    </T.Group>
    <T.Group position={[-0.56, 1.21, 0.72]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_23.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_1_23.geometry} material={gltf.materials.gunmetal} />
    </T.Group>
    <T.Group position={[-0.63, 1.24, 0.61]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_24.geometry} material={gltf.materials.bronze} />
      <T.Mesh geometry={gltf.nodes.primitive_1_24.geometry} material={gltf.materials.mars_2020_02_n} />
    </T.Group>
    <T.Group position={[-0.39, 1.33, -0.6]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_25.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_25.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_2_15.geometry} material={gltf.materials.glass_lens} />
    </T.Group>
    <T.Group position={[0.65, 0.78, 0.67]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_26.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_1_26.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_2_16.geometry} material={gltf.materials.mars_2020_05} />
    </T.Group>
    <T.Group position={[-0.02, 1.16, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_27.geometry} material={gltf.materials.mars_2020_04} />
      <T.Mesh geometry={gltf.nodes.primitive_1_27.geometry} material={gltf.materials.mars_2020_01} />
      <T.Mesh geometry={gltf.nodes.primitive_2_17.geometry} material={gltf.materials.mars_2020_02} />
      <T.Mesh geometry={gltf.nodes.primitive_3_12.geometry} material={gltf.materials.mars_2020_03} />
      <T.Mesh geometry={gltf.nodes.primitive_4_9.geometry} material={gltf.materials.mars_2020_06_n} />
      <T.Mesh geometry={gltf.nodes.primitive_5_9.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_6_6.geometry} material={gltf.materials.gunmetal_dark} />
      <T.Mesh geometry={gltf.nodes.primitive_7_4.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_8_3.geometry} material={gltf.materials.mars_2020_06_brass2} />
      <T.Mesh geometry={gltf.nodes.primitive_9_1.geometry} material={gltf.materials.brass} />
      <T.Mesh geometry={gltf.nodes.primitive_10_1.geometry} material={gltf.materials.grey_brushed} />
      <T.Mesh geometry={gltf.nodes.primitive_11_1.geometry} material={gltf.materials.spring} />
      <T.Mesh geometry={gltf.nodes.primitive_12_1.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_13.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_14.geometry} material={gltf.materials.aluminum_black} />
      <T.Mesh geometry={gltf.nodes.primitive_15.geometry} material={gltf.materials.mars_2020_04_aluminum_r} />
      <T.Mesh geometry={gltf.nodes.primitive_16.geometry} material={gltf.materials.aluminum_black_001} />
      <T.Mesh geometry={gltf.nodes.primitive_17.geometry} material={gltf.materials.blades} />
      <T.Mesh geometry={gltf.nodes.primitive_18.geometry} material={gltf.materials.covidPlaque} />
    </T.Group>
    <T.Group position={[-0.49, 0.88, 1.23]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={0}>
      <T.Mesh geometry={gltf.nodes.primitive_0_28.geometry} material={gltf.materials.sample_handling_door} />
      <T.Mesh geometry={gltf.nodes.primitive_1_28.geometry} material={gltf.materials.gunmetal} />
    </T.Group>
    <T.Group position={[-0.02, 1.16, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_29.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_1_29.geometry} material={gltf.materials.gunmetal_dark} />
      <T.Mesh geometry={gltf.nodes.primitive_2_18.geometry} material={gltf.materials.mars_2020_01} />
    </T.Group>
    <T.Group position={[-0.02, 1.16, 0.08]}>
      <T.Mesh geometry={gltf.nodes.primitive_0_30.geometry} material={gltf.materials.mars_2020_06} />
      <T.Mesh geometry={gltf.nodes.primitive_1_30.geometry} material={gltf.materials.gunmetal_dark} />
      <T.Mesh geometry={gltf.nodes.primitive_2_19.geometry} material={gltf.materials.aluminum} />
      <T.Mesh geometry={gltf.nodes.primitive_3_13.geometry} material={gltf.materials.mars_2020_05} />
      <T.Mesh geometry={gltf.nodes.primitive_4_10.geometry} material={gltf.materials.mars_2020_01} />
    </T.Group>
    <T.Group position={[0.54, 1.15, 0.87]} rotation={[-Math.PI, 0, 0]} scale={0.03}>
      <T.Mesh geometry={gltf.nodes.primitive_0_31.geometry} material={gltf.materials.mars_2020_07} />
      <T.Mesh geometry={gltf.nodes.primitive_1_31.geometry} material={gltf.materials.paint_white_base} />
      <T.Mesh geometry={gltf.nodes.primitive_2_20.geometry} material={gltf.materials.gunmetal} />
      <T.Mesh geometry={gltf.nodes.primitive_3_14.geometry} material={gltf.materials.mars_2020_02_n} />
      <T.Mesh geometry={gltf.nodes.primitive_4_11.geometry} material={gltf.materials.bronze} />
      <T.Mesh geometry={gltf.nodes.primitive_5_10.geometry} material={gltf.materials.mars_2020_02} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hazcams_rear_wiring_1.geometry}
      material={gltf.materials.grey_brushed}
      position={[0.47, 0.78, -1.14]}
    />
    <T.Mesh
      geometry={gltf.nodes.microphones_1.geometry}
      material={gltf.materials.grey_brushed}
      position={[0.61, 1.01, -0.3]}
    />
    <T.Mesh
      geometry={gltf.nodes.RIMFAX_1.geometry}
      material={gltf.materials.mars_2020_01}
      position={[0, 0.78, -1.06]}
    />
    <T.Mesh
      geometry={gltf.nodes.arm_01_joint_1.geometry}
      material={gltf.materials.aluminum}
      position={[-0.41, 0.66, -0.23]}
    />
    <T.Mesh
      geometry={gltf.nodes.arm_02_joint_1.geometry}
      material={gltf.materials.aluminum}
      position={[0.02, 0.7, -0.26]}
    />
    <T.Mesh
      geometry={gltf.nodes.pan_end_cover_1.geometry}
      material={gltf.materials.aluminum}
      position={[-0.19, 0.67, -0.84]}
    />
    <T.Mesh
      geometry={gltf.nodes.calibration_target_bracket_1.geometry}
      material={gltf.materials.gunmetal_dark}
      position={[-0.02, 1.16, 0.08]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
