<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/vibhor/Documents/Projects/Story/Threlte/static/models/rocketisro.glb --root /models/ --printwidth 120 --precision 2
Author: selvinraj (https://sketchfab.com/selvinraj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-isro-a0cb59271cf540bfba324d7c3034d3d3
Title: Rocket  ISRO
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/rocketisro.glb')
  gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
	});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-1.08, 0, -0.22]}>
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Matal_solid_paint_white} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.material} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
