<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/vibhor/Documents/Projects/Story/Threlte/static/models/Spaceship2.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { AddEquation, CustomBlending, Group, LessEqualDepth, OneFactor } from 'three';
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { useTexture } from '@threlte/extras';

  export const ref = new Group()

  const gltf = useGltf('/models/Spaceship2.glb')
  const map = useTexture('textures/energy-beam-opacity.png');

  gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
	});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh0.geometry} material={gltf.materials.mat0} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh1.geometry} material={gltf.materials.mat1} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh2.geometry} material={gltf.materials.mat2} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh3.geometry} material={gltf.materials.mat3} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh4.geometry} material={gltf.materials.mat4} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh5.geometry} material={gltf.materials.mat5} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh6.geometry} material={gltf.materials.mat6} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh7.geometry} material={gltf.materials.mat7} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh8.geometry} material={gltf.materials.mat8} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh9.geometry} material={gltf.materials.mat9} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh10.geometry} material={gltf.materials.mat10} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh11.geometry} material={gltf.materials.mat11} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh12.geometry} material={gltf.materials.mat12} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh13.geometry} material={gltf.materials.mat13} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh14.geometry} material={gltf.materials.mat14} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh15.geometry} material={gltf.materials.mat15} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh16.geometry} material={gltf.materials.mat16} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh17.geometry} material={gltf.materials.mat17} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh18.geometry} material={gltf.materials.mat18} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh19.geometry} material={gltf.materials.mat19} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh20.geometry} material={gltf.materials.mat20} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh21.geometry} material={gltf.materials.mat21} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh22.geometry} material={gltf.materials.mat22} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh23.geometry} material={gltf.materials.mat23} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh24.geometry} material={gltf.materials.mat24} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh25.geometry} material={gltf.materials.mat25} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh26.geometry} material={gltf.materials.mat26} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh27.geometry} material={gltf.materials.mat27} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh28.geometry} material={gltf.materials.mat28} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh29.geometry} material={gltf.materials.mat29} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh30.geometry} material={gltf.materials.mat30} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh31.geometry} material={gltf.materials.mat31} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh32.geometry} material={gltf.materials.mat32} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh33.geometry} material={gltf.materials.mat33} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh34.geometry} material={gltf.materials.mat34} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh35.geometry} material={gltf.materials.mat35} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh36.geometry} material={gltf.materials.mat36} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh37.geometry} material={gltf.materials.mat37} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh38.geometry} material={gltf.materials.mat38} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh39.geometry} material={gltf.materials.mat39} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh40.geometry} material={gltf.materials.mat40} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh41.geometry} material={gltf.materials.mat41} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh42.geometry} material={gltf.materials.mat42} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh43.geometry} material={gltf.materials.mat43} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh44.geometry} material={gltf.materials.mat44} />
    <T.Mesh geometry={gltf.nodes.imagetostl_mesh45.geometry} material={gltf.materials.mat45} />
    {#await map then mapValue}
				<T.Mesh position={[0, 0, -100]} rotation.x={Math.PI * .5}>
					<T.CylinderGeometry args={[10, 25, 200, 15]} />
					<T.MeshBasicMaterial
						color={[1.0, 0.4, 0.02]}
						alphaMap={mapValue}
						transparent
						blending={CustomBlending}
						blendDst={OneFactor}
						blendEquation={AddEquation}
					/>
				</T.Mesh>
			{/await}
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
